# Generated by Django 4.2 on 2023-04-19 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InformacionUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        default="default_profile.png",
                        null=True,
                        upload_to="perfil/",
                    ),
                ),
                ("numerotelefonico", models.CharField(max_length=50, null=True)),
                ("genero", models.CharField(max_length=10, null=True)),
                ("direccion", models.CharField(max_length=60, null=True)),
                ("fechanacimiento", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
