# Generated by Django 4.2 on 2023-07-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="informacionusuario",
            name="facebook",
            field=models.URLField(default=1, null=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="informacionusuario",
            name="instagram",
            field=models.URLField(default=2, null=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="informacionusuario",
            name="twiter",
            field=models.URLField(default=21, null=None),
            preserve_default=False,
        ),
    ]
