# Generated by Django 5.2.1 on 2025-05-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacionusuario',
            old_name='fechanacimiento',
            new_name='born_date',
        ),
        migrations.RenameField(
            model_name='informacionusuario',
            old_name='numerotelefonico',
            new_name='phone_number',
        ),
    ]
