# Generated by Django 4.2 on 2023-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informacionusuario",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="perfil/"),
        ),
    ]
