# Generated by Django 5.2.1 on 2025-05-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_fechanacimiento_informacionusuario_born_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacionusuario',
            old_name='direccion',
            new_name='address',
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
