# Generated by Django 4.2 on 2023-04-11 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0004_paradero_alter_empresa_numero_resolucion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("RUC", "RUC"),
                            ("CARNET", "Carnet de Extranjería"),
                        ],
                        max_length=10,
                    ),
                ),
                ("abreviatura", models.CharField(max_length=10)),
                ("descripcion", models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
                (
                    "tipodocumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persona.tipodocumento",
                    ),
                ),
            ],
        ),
    ]
