# Generated by Django 4.2 on 2023-04-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="nombre",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
