# Generated by Django 4.2 on 2023-05-11 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=70)),
                ("flota", models.IntegerField()),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("numero_resolucion", models.CharField(max_length=100)),
                ("fecha_resolucion", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("federacion", models.CharField(max_length=50)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Empresas",},
        ),
        migrations.CreateModel(
            name="Federacion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Federaciones",},
        ),
        migrations.CreateModel(
            name="Paradero",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("numero_resolucion", models.CharField(max_length=100)),
                ("fecha_resolcuion", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licencia",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_resolucion", models.CharField(max_length=100)),
                ("fecha_inicial", models.DateField()),
                ("fecha_final", models.DateField()),
                ("Recibo_caja", models.CharField(max_length=180)),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Licencias",},
        ),
        migrations.CreateModel(
            name="Empresa_paradero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
                (
                    "paradero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.paradero",
                    ),
                ),
            ],
        ),
    ]
