# Generated by Django 4.2 on 2023-04-11 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=70)),
                ("flota", models.IntegerField()),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("numero_resolucion", models.IntegerField()),
                ("fecha_resolucion", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Empresas",},
        ),
        migrations.CreateModel(
            name="Federacion",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Federaciones",},
        ),
        migrations.CreateModel(
            name="Licencia",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_resolucion", models.IntegerField()),
                ("fecha_inicial", models.DateTimeField()),
                ("fecha_final", models.DateTimeField()),
                ("Recibo_caja", models.CharField(max_length=180)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Licencias",},
        ),
    ]
