# Generated by Django 4.2 on 2023-04-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licencia",
            name="fecha_actualizacion",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="licencia",
            name="fecha_creacion",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="federacion",
            name="fecha_actualizacion",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="federacion",
            name="fecha_creacion",
            field=models.DateField(auto_now=True),
        ),
    ]
