# Generated by Django 4.2 on 2023-04-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "empresa",
            "0002_licencia_fecha_actualizacion_licencia_fecha_creacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="federacion",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="federacion",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="licencia",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="licencia",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="licencia", name="fecha_final", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="licencia", name="fecha_inicial", field=models.DateField(),
        ),
    ]
