# Generated by Django 4.2 on 2023-07-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_alter_licencia_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licencia",
            name="pdf",
            field=models.FileField(null=True, upload_to="pdfs/"),
        ),
    ]
