# Generated by Django 4.2 on 2023-04-11 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_alter_federacion_fecha_actualizacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paradero",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("numero_resolucion", models.CharField(max_length=100)),
                ("fecha_resolcuion", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="empresa",
            name="numero_resolucion",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="licencia",
            name="numero_resolucion",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Empresa_paradero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
                (
                    "paradero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.paradero",
                    ),
                ),
            ],
        ),
    ]
