# Generated by Django 4.2 on 2023-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0005_alter_licencia_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa", name="flota", field=models.CharField(max_length=50),
        ),
    ]
