# Generated by Django 4.2 on 2023-07-20 18:10

from django.db import migrations, models
import empresa.models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0006_alter_empresa_flota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licencia",
            name="pdf",
            field=models.FileField(
                null=True, upload_to=empresa.models.file_upload_path
            ),
        ),
    ]
