# Generated by Django 4.2 on 2023-05-11 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persona", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descripcion", models.CharField(max_length=180)),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=180)),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Marcas",},
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                ("codigo", models.IntegerField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=180)),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vehiculo.marca"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Modelos",},
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "codigo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("numero_placa", models.CharField(max_length=10, unique=True)),
                ("numeracion", models.CharField(max_length=10, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("año", models.IntegerField()),
                (
                    "conductor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculo_conducido",
                        to="persona.persona",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresa.empresa",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculo.estado",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculo.modelo",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiculo_propietario",
                        to="persona.persona",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
